### ISSUE TITLE
Python OpenAI Lambda Layer

### ISSUE THREAD

**Issue by erenyasarkurt** [mthenw/awesome-layers#100]
Hey, it'd be great if you could add the layer below:

https://github.com/erenyasarkurt/OpenAI-AWS-Lambda-Layer

**Comment by mthenw** [comment]
Hey, can you create a PR?

**Comment by erenyasarkurt** [comment]
Done: https://github.com/mthenw/awesome-layers/pull/101

Thanks!

**Comment by erenyasarkurt** [comment]
Sorry, the order was wrong I pushed a new commit (bd1f04f) to the branch.
