### ISSUE TITLE
java 11 layer cannot be deployed

### ISSUE THREAD

**Issue by amihaylov** [mthenw/awesome-layers#61]
Trying to deploy https://github.com/andthearchitect/aws-lambda-java-runtime 
with AWS cli will give you
`An error occurred (RequestEntityTooLargeException) when calling the PublishLayerVersion operation: Request must be smaller than 69905067 bytes for the PublishLayerVersion operation
`
since the zip is 120MB. Manually trying to deploy via the console with a preuploaded S3 object will return 
`Failed to create layer version: Unzipped size must be smaller than 262144000 bytes`
since unpacked size is ~290MB so I guess it is unusable. Is someone else using JRE layer?

**Comment by mthenw** [comment]
Hey @amihaylov,

I don't think that I'm able to help you as I don't own https://github.com/andthearchitect/aws-lambda-java-runtime repo.
